workflows:
  ios-workflow:
    name: Adaptalyfe iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.adaptalyfe.app
        certificate_reference: ADAPTALYFE_DISTRIBUTION_CERT
        provisioning_profile_reference: ADAPTALYFE_APP_STORE_PROFILE
      vars:
        CAPACITOR_PROJECT: "true"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      - name: Build web app
        script: |
          npm run build
      - name: Initialize Capacitor iOS
        script: |
          npx cap add ios || echo "iOS already added"
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true