[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Skipping frontend build - Express will serve dynamically"']

[start]
cmd = 'npm start'