[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs-20_x"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci --omit=dev && npm install -g esbuild"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300
startCommand = "npm run start"

[variables]
NODE_ENV = "production"