[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[deploy.healthcheck]]
httpPath = "/api/health"
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
failureThreshold = 3