services:
  - type: web
    name: adaptalyfe-cache-bust
    env: node
    plan: starter
    buildCommand: |
      echo "🚀 Standalone build started - no Vite dependencies"
      rm -rf node_modules/.cache dist/ .npm
      npm ci --cache /tmp/npm-cache-$(date +%s)
      npm run build
      cp production-index-cache-bust.html dist/public/index.html
      echo "📦 Building ultra-minimal server (absolute minimum dependencies)"
      esbuild server/ultra-minimal.ts --platform=node --packages=external --bundle --format=esm --outfile=ultra-app.js
      echo "✅ Ultra-minimal build complete - testing basic functionality"
    startCommand: node ultra-app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CACHE_BUSTER
        value: "2025-09-03-v2"
      - key: DATABASE_URL
        fromDatabase:
          name: adaptalyfe-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

databases:
  - name: adaptalyfe-db
    databaseName: adaptalyfe
    user: adaptalyfe_user
    plan: starter