services:
  - type: web
    name: adaptalyfe
    env: node
    plan: starter
    buildCommand: npm install && npm run build && esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outfile=dist/production.js
    startCommand: node dist/production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: adaptalyfe-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false

databases:
  - name: adaptalyfe-db
    databaseName: adaptalyfe
    user: adaptalyfe_user
    plan: starter