require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

platform :ios, '11.0'
prepare_react_native_project!

target 'MobileBuilderPro' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end